CREATE TABLE IF NOT EXISTS "users" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"email" VARCHAR(100) UNIQUE NOT NULL,
	"password_hash" VARCHAR(255) NOT NULL,
	"role" VARCHAR(20) DEFAULT 'Customer'
);

CREATE TABLE IF NOT EXISTS "employees" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id" INT UNIQUE NOT NULL,
	"first_name" VARCHAR(50) NOT NULL,
	"last_name" VARCHAR(50) NOT NULL,
	"phone" VARCHAR(20) UNIQUE,
	"position" VARCHAR(50),
	CONSTRAINT "fk_employees_user"
		FOREIGN KEY ("user_id") 
		REFERENCES "users" ("id")
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "customers" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"user_id" INT UNIQUE NOT NULL,
	"first_name" VARCHAR(50),
	"last_name" VARCHAR(50),
	"phone" VARCHAR(20) UNIQUE,
	"address" VARCHAR(200),
	CONSTRAINT "fk_customers_user"
		FOREIGN KEY ("user_id") 
		REFERENCES "users" ("id")
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "categories" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(50),
	"description" TEXT
);

CREATE TABLE IF NOT EXISTS "subcategories" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"category_id" BIGINT,
	"name" VARCHAR(50),
	"description" TEXT,
	CONSTRAINT "fk_subcategories_category"
		FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "products" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(50),
	"description" TEXT,
	"price" DECIMAL(10, 2) NOT NULL,
	"category_id" BIGINT,
	"subcategory_id" BIGINT,
	CONSTRAINT "fk_products_category"
		FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE SET NULL,
	CONSTRAINT "fk_products_subcategory"
		FOREIGN KEY ("subcategory_id") REFERENCES "subcategories" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "shopping_carts" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"customer_id" BIGINT UNIQUE,
	CONSTRAINT "fk_carts_customer"
		FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "cart_items" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"cart_id" BIGINT,
	"product_id" BIGINT,
	"quantity" INT NOT NULL CHECK (quantity > 0),
	CONSTRAINT "fk_cart_items_cart"
		FOREIGN KEY ("cart_id") REFERENCES "shopping_carts" ("id") ON DELETE CASCADE,
	CONSTRAINT "fk_cart_items_product"
		FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "orders" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"customer_id" BIGINT,
	"order_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"status" VARCHAR(20),
	CONSTRAINT "fk_orders_customer"
		FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS "order_items" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"order_id" BIGINT,
	"product_id" BIGINT,
	"quantity" INT NOT NULL CHECK (quantity > 0),
	"price" DECIMAL(10, 2),
	CONSTRAINT "fk_order_items_order"
		FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE,
	CONSTRAINT "fk_order_items_product"
		FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "order_status_history" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"order_id" BIGINT NOT NULL,
	"status" VARCHAR(20) DEFAULT 'Pending' NOT NULL,
	"status_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "fk_order_status_history_order"
		FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "payments" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"order_id" BIGINT NOT NULL,
	"payment_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"amount" DECIMAL(10, 2) NOT NULL,
	"payment_method" VARCHAR(50) NOT NULL,
	"status" VARCHAR(20) NOT NULL,
	CONSTRAINT "fk_payments_order"
		FOREIGN KEY ("order_id") REFERENCES "orders" ("id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "reviews" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "rating" INT,
    "comment" VARCHAR(100),
    "review_date" DATE,
    CONSTRAINT "fk_reviews_customer" 
        FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE SET NULL,
    CONSTRAINT "fk_reviews_product" 
        FOREIGN KEY ("product_id") REFERENCES "products" ("id")
);

CREATE TABLE IF NOT EXISTS "favorites" (
	"id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"customer_id" INT NOT NULL,
	"product_id" INT NOT NULL,
	"created_at" TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT "fk_favorites_customer"
		FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE CASCADE,
	CONSTRAINT "fk_favorites_product"
		FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE,
	CONSTRAINT "uq_favorites_customer_product" UNIQUE ("customer_id", "product_id")
);

