CREATE TABLE IF NOT EXISTS "employees" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"first_name" VARCHAR(50) NOT NULL,
	"last_name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(100) UNIQUE,
	"phone" VARCHAR(20) UNIQUE,
	"position" VARCHAR(50),
	"role" INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS "categories" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(50),
	"description" TEXT
);

CREATE TABLE IF NOT EXISTS "customers" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"first_name" VARCHAR(50),
	"last_name" VARCHAR(50),
	"email" VARCHAR(100) NOT NULL UNIQUE,
	"phone" VARCHAR(20) UNIQUE,
	"address" VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS "orders" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"customer_id" BIGINT,
	"order_date" DATE DEFAULT CURRENT_DATE,
	"status" VARCHAR(20),
	CONSTRAINT "fk_orders_customer"
		FOREIGN KEY ("customer_id") REFERENCES "customers" ("id")
);

CREATE TABLE IF NOT EXISTS "subcategories" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"category_id" BIGINT,
	"name" VARCHAR(50),
	"description" TEXT,
	CONSTRAINT "fk_subcategories_category"
		FOREIGN KEY ("category_id") REFERENCES "categories" ("id")
);

CREATE TABLE IF NOT EXISTS "products" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"name" VARCHAR(50),
	"description" TEXT,
	"price" DECIMAL(10, 2) NOT NULL,
	"category_id" BIGINT,
	"subcategory_id" BIGINT,
	CONSTRAINT "fk_products_category"
		FOREIGN KEY ("category_id") REFERENCES "categories" ("id"),
	CONSTRAINT "fk_products_subcategory"
		FOREIGN KEY ("subcategory_id") REFERENCES "subcategories" ("id")
);

CREATE TABLE IF NOT EXISTS "shopping_carts" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"customer_id" BIGINT,
	CONSTRAINT "fk_carts_customer"
		FOREIGN KEY ("customer_id") REFERENCES "customers" ("id")
);

CREATE TABLE IF NOT EXISTS "cart_items" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"cart_id" BIGINT,
	"product_id" BIGINT,
	"quantity" INT,
	CONSTRAINT "fk_cart_items_cart"
		FOREIGN KEY ("cart_id") REFERENCES "shopping_carts" ("id"),
	CONSTRAINT "fk_cart_items_product"
		FOREIGN KEY ("product_id") REFERENCES "products" ("id")
);

CREATE TABLE IF NOT EXISTS "order_items" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"order_id" BIGINT,
	"product_id" BIGINT,
	"quantity" INT,
	"price" DECIMAL(10, 2),
	CONSTRAINT "fk_order_items_order"
		FOREIGN KEY ("order_id") REFERENCES "orders" ("id"),
	CONSTRAINT "fk_order_items_product"
		FOREIGN KEY ("product_id") REFERENCES "products" ("id")
);

CREATE TABLE IF NOT EXISTS "payments" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"order_id" BIGINT NOT NULL,
	"payment_date" DATE DEFAULT CURRENT_DATE NOT NULL,
	"amount" DECIMAL(10, 2) NOT NULL,
	"payment_method" VARCHAR(50) NOT NULL,
	CONSTRAINT "fk_payments_order"
		FOREIGN KEY ("order_id") REFERENCES "orders" ("id")
);

CREATE TABLE IF NOT EXISTS "reviews" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "customer_id" BIGINT NOT NULL,
    "product_id" BIGINT NOT NULL,
    "rating" INT,
    "comment" VARCHAR(100),
    "review_date" DATE,
    CONSTRAINT "fk_reviews_customer" 
        FOREIGN KEY ("customer_id") REFERENCES "customers" ("id"),
    CONSTRAINT "fk_reviews_product" 
        FOREIGN KEY ("product_id") REFERENCES "products" ("id")
);