using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Testcontainers.PostgreSql;
using Testcontainers.Redis;
using Xunit;
using Npgsql;
using System.Threading.Tasks;

namespace Backend.Tests.IntegrationTests;

public class CustomApiFactory : WebApplicationFactory<Program>, IAsyncLifetime
{
    private readonly PostgreSqlContainer _dbContainer = new PostgreSqlBuilder()
        .WithImage("postgres:15-alpine")
        .WithDatabase("test_db")
        .WithUsername("postgres")
        .WithPassword("postgres")
        .Build();
    
    private readonly RedisContainer _redisContainer = new RedisBuilder()
        .WithImage("redis:7-alpine")
        .Build();

    public CustomApiFactory()
    {
        Environment.SetEnvironmentVariable("JWT_SECRET_KEY", "A_Very_Long_Super_Secret_Key_For_Testing_Only_12345!");
        Environment.SetEnvironmentVariable("JwtSettings__Issuer", "TestIssuer");
        Environment.SetEnvironmentVariable("JwtSettings__Audience", "TestAudience");
        Environment.SetEnvironmentVariable("DB_PASSWORD", "dummy_db_password");
        Environment.SetEnvironmentVariable("REDIS_PASSWORD", "dummy_redis_password");
    }

    public async ValueTask InitializeAsync()
    {
        await Task.WhenAll(_dbContainer.StartAsync(), _redisContainer.StartAsync());

        await InitializeDatabaseAsync();
    }

    private async Task InitializeDatabaseAsync()
    {
        var connectionString = _dbContainer.GetConnectionString();
        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync();

        // hier 01-schema.sql
        var sql = @"
            CREATE TABLE IF NOT EXISTS ""users"" (
                ""id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""email"" VARCHAR(100) UNIQUE NOT NULL,
                ""password_hash"" VARCHAR(255) NOT NULL,
                ""role"" VARCHAR(20) DEFAULT 'Customer'
            );

            CREATE TABLE IF NOT EXISTS ""customers"" (
                ""id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""user_id"" INT UNIQUE NOT NULL,
                ""first_name"" VARCHAR(50),
                ""last_name"" VARCHAR(50),
                ""phone"" VARCHAR(20) UNIQUE,
                ""address"" VARCHAR(200),
                CONSTRAINT ""fk_customers_user""
                    FOREIGN KEY (""user_id"") 
                    REFERENCES ""users"" (""id"")
                    ON DELETE CASCADE
            );
        ";

        // Voer het script uit
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }

    // Overschrijf de config, pak de connectionstring van test_db
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureAppConfiguration((context, config) =>
        {
            config.AddInMemoryCollection(new Dictionary<string, string?>
            {
                { "ConnectionStrings:DefaultConnection", _dbContainer.GetConnectionString() },
                { "ConnectionStrings:RedisConnection", _redisContainer.GetConnectionString() }
            });
        });
    }

    public new async ValueTask DisposeAsync()
    {
        await Task.WhenAll(_dbContainer.DisposeAsync(), _redisContainer.DisposeAsync());
    }
}