using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Testcontainers.PostgreSql;
using Testcontainers.Redis;
using Xunit;
using Npgsql;
using System.Threading.Tasks;

namespace Backend.Tests.IntegrationTests;

public class CustomApiFactory : WebApplicationFactory<Program>, IAsyncLifetime
{
    private readonly PostgreSqlContainer _dbContainer = new PostgreSqlBuilder()
        .WithImage("postgres:15-alpine")
        .WithDatabase("test_db")
        .WithUsername("postgres")
        .WithPassword("postgres")
        .Build();

    private readonly RedisContainer _redisContainer = new RedisBuilder()
        .WithImage("redis:7-alpine")
        .Build();

    public CustomApiFactory()
    {
        Environment.SetEnvironmentVariable("JWT_SECRET_KEY", "A_Very_Long_Super_Secret_Key_For_Testing_Only_12345!");
        Environment.SetEnvironmentVariable("JwtSettings__Key", "A_Very_Long_Super_Secret_Key_For_Testing_Only_12345!");
        Environment.SetEnvironmentVariable("JwtSettings__Issuer", "TestIssuer");
        Environment.SetEnvironmentVariable("JwtSettings__Audience", "TestAudience");
    }

    public async ValueTask InitializeAsync()
    {
        await Task.WhenAll(_dbContainer.StartAsync(), _redisContainer.StartAsync());

        await InitializeDatabaseAsync();
    }

    private async Task InitializeDatabaseAsync()
    {
        var connectionString = _dbContainer.GetConnectionString();
        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync();

        // Testdatabase schema.
        // Deze tabellen zijn nodig voor de bestaande auth/employee tests
        // en voor de products/reviews integration tests.
        var sql = @"
            -- 1. Independent Tables
            CREATE TABLE IF NOT EXISTS ""users"" (
                ""id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""email"" VARCHAR(100) UNIQUE NOT NULL,
                ""password_hash"" VARCHAR(255) NOT NULL,
                ""role"" VARCHAR(20) DEFAULT 'Customer'
            );

            CREATE TABLE IF NOT EXISTS ""categories"" (
                ""id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""name"" VARCHAR(50),
                ""description"" TEXT
            );

            -- 2. First-Level Dependencies
            CREATE TABLE IF NOT EXISTS ""customers"" (
                ""id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""user_id"" INT UNIQUE NOT NULL,
                ""first_name"" VARCHAR(50),
                ""last_name"" VARCHAR(50),
                ""phone"" VARCHAR(20) UNIQUE,
                ""address"" VARCHAR(200),
                CONSTRAINT ""fk_customers_user""
                    FOREIGN KEY (""user_id"") 
                    REFERENCES ""users"" (""id"")
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS ""employees"" (
                ""id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""user_id"" INT UNIQUE NOT NULL,
                ""first_name"" VARCHAR(50) NOT NULL,
                ""last_name"" VARCHAR(50) NOT NULL,
                ""phone"" VARCHAR(20) UNIQUE,
                ""position"" VARCHAR(50),
                CONSTRAINT ""fk_employees_user""
                    FOREIGN KEY (""user_id"")
                    REFERENCES ""users"" (""id"")
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS ""subcategories"" (
                ""id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""category_id"" BIGINT,
                ""name"" VARCHAR(50),
                ""description"" TEXT,
                CONSTRAINT ""fk_subcategories_category""
                    FOREIGN KEY (""category_id"") REFERENCES ""categories"" (""id"") ON DELETE CASCADE
            );

            -- 3. Second-Level Dependencies
            CREATE TABLE IF NOT EXISTS ""products"" (
                ""id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""name"" VARCHAR(50),
                ""description"" TEXT,
                ""price"" DECIMAL(10, 2) NOT NULL,
                ""category_id"" BIGINT,
                ""subcategory_id"" BIGINT,
                CONSTRAINT ""fk_products_category""
                    FOREIGN KEY (""category_id"") REFERENCES ""categories"" (""id"") ON DELETE SET NULL,
                CONSTRAINT ""fk_products_subcategory""
                    FOREIGN KEY (""subcategory_id"") REFERENCES ""subcategories"" (""id"") ON DELETE SET NULL
            );

            -- 4. Third-Level Dependencies (Rely on products/customers)
            CREATE TABLE IF NOT EXISTS ""reviews"" (
                ""id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""customer_id"" INT NOT NULL,
                ""product_id"" BIGINT NOT NULL,
                ""rating"" INT NOT NULL,
                ""comment"" VARCHAR(100),
                ""review_date"" DATE DEFAULT CURRENT_DATE,
                CONSTRAINT ""fk_reviews_customer""
                    FOREIGN KEY (""customer_id"")
                    REFERENCES ""customers"" (""id"")
                    ON DELETE CASCADE,
                CONSTRAINT ""fk_reviews_product""
                    FOREIGN KEY (""product_id"")
                    REFERENCES ""products"" (""id"")
                    ON DELETE CASCADE
            );

            CREATE TABLE IF NOT EXISTS ""favorites"" (
                ""id"" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""customer_id"" INT NOT NULL,
                ""product_id"" BIGINT NOT NULL,
                ""created_at"" TIMESTAMP NOT NULL DEFAULT NOW(),
                CONSTRAINT ""fk_favorites_customer""
                    FOREIGN KEY (""customer_id"") REFERENCES ""customers"" (""id"") ON DELETE CASCADE,
                CONSTRAINT ""fk_favorites_product""
                    FOREIGN KEY (""product_id"") REFERENCES ""products"" (""id"") ON DELETE CASCADE,
                CONSTRAINT ""uq_favorites_customer_product"" UNIQUE (""customer_id"", ""product_id"")
            );

            CREATE TABLE IF NOT EXISTS ""orders"" (
                ""id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""customer_id"" INT,
                ""order_date"" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                ""status"" VARCHAR(20),
                CONSTRAINT ""fk_orders_customer""
                    FOREIGN KEY (""customer_id"") REFERENCES ""customers"" (""id"") ON DELETE SET NULL
            );

            -- 5. Fourth-Level Dependencies
            CREATE TABLE IF NOT EXISTS ""order_items"" (
                ""id"" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""order_id"" BIGINT,
                ""product_id"" BIGINT,
                ""quantity"" INT NOT NULL CHECK (quantity > 0),
                ""price"" DECIMAL(10, 2),
                CONSTRAINT ""fk_order_items_order""
                    FOREIGN KEY (""order_id"") REFERENCES ""orders"" (""id"") ON DELETE CASCADE,
                CONSTRAINT ""fk_order_items_product""
                    FOREIGN KEY (""product_id"") REFERENCES ""products"" (""id"") ON DELETE RESTRICT
            );
        ";

        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }

    // Overschrijf de config, pak de connectionstring van test_db
    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureAppConfiguration((context, config) =>
        {
            config.AddInMemoryCollection(new Dictionary<string, string?>
            {
                { "ConnectionStrings:DefaultConnection", _dbContainer.GetConnectionString() },
                { "ConnectionStrings:RedisDefaultConnection", _redisContainer.GetConnectionString() },

                { "DB_PASSWORD", "dummy_db_password" },
                { "REDIS_PASSWORD", "dummy_redis_password" },

                { "JWT_SECRET_KEY", "A_Very_Long_Super_Secret_Key_For_Testing_Only_12345!" },
                { "JwtSettings:Key", "A_Very_Long_Super_Secret_Key_For_Testing_Only_12345!" },
                { "JwtSettings:Issuer", "TestIssuer" },
                { "JwtSettings:Audience", "TestAudience" }
            });
        });
    }

    public new async ValueTask DisposeAsync()
    {
        await _dbContainer.DisposeAsync();
        await _redisContainer.DisposeAsync();
    }
}
