name: Deploy to VM

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Stack
        run: |
          cd /home/ubuntu-1104947/DT-website
          git pull origin main
          docker-compose up -d --build
